# Generated by Django 3.0.6 on 2020-06-06 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Manufacturer name')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(max_length=40, verbose_name='Serie')),
                ('model', models.CharField(blank=True, max_length=40, null=True, verbose_name='Model')),
                ('storage_type', models.CharField(choices=[('M.2 SSD', 'M.2 SSD'), ('SSD', 'SSD'), ('HDD 5.4K RPM', 'HDD 5.4K RPM'), ('HDD 7.2K RPM', 'HDD 7.2K RPM'), ('HDD 10K RPM', 'HDD 10K RPM')], default='SSD', max_length=20, verbose_name='Type')),
                ('capacity', models.IntegerField(choices=[(128, '128 GB'), (240, '240 GB'), (480, '480 GB'), (512, '512 GB'), (960, '960 GB'), (1024, '1 TB'), (2048, '2 TB'), (3072, '3 TB'), (4096, '4 TB')], default=240, verbose_name='Capacity')),
                ('form_factor', models.CharField(choices=[('M.2 2242', 'M.2 2242'), ('M.2 2260', 'M.2 2260'), ('M.2 2280', 'M.2 2280'), ('M.2 22110', 'M.2 22110'), ('2.5"', '2.5"'), ('3.5"', '3.5"')], default='2.5"', max_length=20, verbose_name='Form Factor')),
                ('manufacturer_website', models.URLField(max_length=500, verbose_name='Manufacturer website')),
                ('img1_url', models.URLField(max_length=500, verbose_name='Image url')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pc.Manufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='Ram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(max_length=30, verbose_name='Serie')),
                ('model', models.CharField(max_length=30, verbose_name='Model')),
                ('speed', models.IntegerField(choices=[(2400, '2400 MHz'), (2600, '2600 MHz'), (2666, '2666 MHz'), (2933, '2933 MHz'), (3000, '3000 MHz'), (3200, '3200 MHz'), (3333, '3333 MHz'), (3466, '3466 MHz'), (3600, '3600 MHz'), (3800, '3800 MHz'), (4000, '4000 MHz'), (4266, '4266 MHz')], default=3000, verbose_name='Speed')),
                ('size', models.IntegerField(choices=[(4, '4 GB'), (8, '8 GB'), (16, '16 GB'), (32, '32 GB'), (64, '64 GB'), (128, '128 GB')], default=8, verbose_name='Total Size')),
                ('size_kit', models.CharField(choices=[('4x1', '4GB'), ('4x2', '8GB (2x4GB)'), ('8x1', '8GB'), ('16x1', '16GB'), ('4x4', '16GB (4x4GB)'), ('8x2', '16GB (2x8GB)'), ('32x1', '32GB'), ('8x4', '32GB (4x8GB)'), ('16x2', '32GB (2x16GB)'), ('16x4', '64GB (4x16GB)'), ('32x2', '64GB (2x32GB)'), ('32x4', '128GB (4x32GB)')], default='8x1', max_length=4, verbose_name='Size Kit')),
                ('manufacturer_website', models.URLField(max_length=500, verbose_name='Manufacturer website')),
                ('img1_url', models.URLField(max_length=500, verbose_name='Image url')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pc.Manufacturer')),
            ],
            options={
                'verbose_name': 'RAM',
                'verbose_name_plural': 'RAMs',
            },
        ),
        migrations.CreateModel(
            name='Psu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(max_length=20, verbose_name='Serie')),
                ('model', models.CharField(max_length=20, verbose_name='Model')),
                ('certified', models.CharField(choices=[('Standard', 'Standard'), ('Bronze', 'Bronze'), ('Silver', 'Silver'), ('Gold', 'Gold'), ('Platinum', 'Platinum'), ('Titanium', 'Titanium')], default='Standard', max_length=20, verbose_name='Certified')),
                ('manufacturer_website', models.URLField(max_length=500, verbose_name='Manufacturer website')),
                ('img1_url', models.URLField(max_length=500, verbose_name='Image url')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pc.Manufacturer')),
            ],
            options={
                'verbose_name': 'PSU',
                'verbose_name_plural': 'PSUs',
            },
        ),
        migrations.CreateModel(
            name='Gpu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(max_length=30, verbose_name='Serie')),
                ('model', models.CharField(max_length=50, verbose_name='Model')),
                ('vram_size', models.IntegerField(default=4, verbose_name='VRAM size (GB)')),
                ('manufacturer_website', models.URLField(max_length=500, verbose_name='Manufacturer website')),
                ('img1_url', models.URLField(max_length=500, verbose_name='Image url')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pc.Manufacturer')),
            ],
            options={
                'verbose_name': 'GPU',
                'verbose_name_plural': 'GPUs',
            },
        ),
        migrations.CreateModel(
            name='Cpu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(max_length=30, verbose_name='Serie')),
                ('model', models.CharField(max_length=30, verbose_name='Model')),
                ('manufacturer_website', models.URLField(max_length=500, verbose_name='Manufacturer website')),
                ('img1_url', models.URLField(max_length=500, verbose_name='Image url')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pc.Manufacturer')),
            ],
            options={
                'verbose_name': 'CPU',
                'verbose_name_plural': 'CPUs',
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(max_length=20, verbose_name='Serie')),
                ('model', models.CharField(max_length=20, verbose_name='Model')),
                ('manufacturer_website', models.URLField(max_length=500, verbose_name='Manufacturer website')),
                ('img1_url', models.URLField(max_length=500, verbose_name='Image url')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pc.Manufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(max_length=30, verbose_name='Serie')),
                ('model', models.CharField(max_length=30, verbose_name='Model')),
                ('manufacturer_website', models.URLField(max_length=500, verbose_name='Manufacturer website')),
                ('img1_url', models.URLField(max_length=500, verbose_name='Image url')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pc.Manufacturer')),
            ],
        ),
    ]
