# Generated by Django 3.0.6 on 2020-06-08 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storage',
            options={'ordering': ['manufacturer']},
        ),
        migrations.AlterField(
            model_name='psu',
            name='serie',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Serie'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='capacity',
            field=models.IntegerField(choices=[(128, '128 GB'), (240, '240 GB'), (256, '256 GB'), (480, '480 GB'), (512, '512 GB'), (960, '960 GB'), (1024, '1 TB'), (2048, '2 TB'), (3072, '3 TB'), (4096, '4 TB')], default=240, verbose_name='Capacity'),
        ),
    ]
