# Generated by Django 3.0.6 on 2020-05-30 06:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='PC name')),
                ('budget', models.IntegerField(blank=True, null=True, verbose_name='Budget')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Create at')),
            ],
            options={
                'verbose_name': 'PC',
                'verbose_name_plural': 'PCs',
            },
        ),
        migrations.CreateModel(
            name='Pc_storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Pc')),
                ('store_storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Store_storage')),
            ],
            options={
                'verbose_name': 'PC Storage',
                'verbose_name_plural': 'PC Storages',
            },
        ),
        migrations.CreateModel(
            name='Pc_ram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Pc')),
                ('store_ram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Store_ram')),
            ],
            options={
                'verbose_name': 'PC RAM',
                'verbose_name_plural': 'PC RAMs',
            },
        ),
        migrations.CreateModel(
            name='Pc_psu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Pc')),
                ('store_psu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Store_psu')),
            ],
            options={
                'verbose_name': 'PC PSU',
                'verbose_name_plural': 'PC PSUs',
            },
        ),
        migrations.CreateModel(
            name='Pc_gpu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Pc')),
                ('store_gpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Store_gpu')),
            ],
            options={
                'verbose_name': 'PC GPU',
                'verbose_name_plural': 'PC GPUs',
            },
        ),
        migrations.CreateModel(
            name='Pc_cpu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Pc')),
                ('store_cpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Store_cpu')),
            ],
            options={
                'verbose_name': 'PC CPU',
                'verbose_name_plural': 'PC CPUs',
            },
        ),
        migrations.CreateModel(
            name='Pc_case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Pc')),
                ('store_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Store_case')),
            ],
            options={
                'verbose_name': 'PC Case',
                'verbose_name_plural': 'PC Cases',
            },
        ),
        migrations.CreateModel(
            name='Pc_board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Pc')),
                ('store_board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Store_board')),
            ],
            options={
                'verbose_name': 'PC Board',
                'verbose_name_plural': 'PC Boards',
            },
        ),
        migrations.AddField(
            model_name='pc',
            name='board',
            field=models.ManyToManyField(through='user.Pc_board', to='store.Store_board'),
        ),
        migrations.AddField(
            model_name='pc',
            name='case',
            field=models.ManyToManyField(through='user.Pc_case', to='store.Store_case'),
        ),
        migrations.AddField(
            model_name='pc',
            name='cpu',
            field=models.ManyToManyField(through='user.Pc_cpu', to='store.Store_cpu'),
        ),
        migrations.AddField(
            model_name='pc',
            name='gpu',
            field=models.ManyToManyField(through='user.Pc_gpu', to='store.Store_gpu'),
        ),
        migrations.AddField(
            model_name='pc',
            name='psu',
            field=models.ManyToManyField(through='user.Pc_psu', to='store.Store_psu'),
        ),
        migrations.AddField(
            model_name='pc',
            name='ram',
            field=models.ManyToManyField(through='user.Pc_ram', to='store.Store_ram'),
        ),
        migrations.AddField(
            model_name='pc',
            name='storage',
            field=models.ManyToManyField(through='user.Pc_storage', to='store.Store_storage'),
        ),
        migrations.AddField(
            model_name='pc',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pcs', to=settings.AUTH_USER_MODEL),
        ),
    ]
